region        = "us-east-2"
project_name  = "zomato"
project_env   = "development"
instance_type = "t2.micro"
instance_ami  = "ami-02bf8ce06a8ed6092"
key_name      = "zomato-dev"
domain_name   = "dev.sreerag.online"
hostname      = "zomato"
